name: Improvement
description: Improve this tool
labels: [documentation]
body:
  - type: textarea
    attributes:
      label: Describe the improvement you have made of this tool (Must be detailed)
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Show image/video evidence that shows the improvement of this tool (If applicable)
    validations:
      required: false
